sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t dakl/arm32-python-alpine-qemu:build .
# test image
- docker run dakl/arm32-python-alpine-qemu:build uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag hypriot/rpi-alpine:build hypriot/rpi-alpine:$TAG
    docker tag hypriot/rpi-alpine:build hypriot/rpi-alpine:latest
    docker push hypriot/rpi-alpine:$TAG
    docker push hypriot/rpi-alpine:latest
  fi